### ISSUE TITLE
When to support null safety

### ISSUE THREAD

**Issue by mohenaxiba** [itso-developer/secure_biometric_storage#1]
points: Package does not opt in to null safety.
Package language version (indicated by the sdk constraint `>=2.7.0 <3.0.0`) is less than 2.12.

**Comment by abdallah-odeh** [comment]
Why would this issue be closed if it's not solved or implemented & there isn't any explanation here!

**Comment by loposkin** [comment]
Hi @abdallah-odeh,

null safety version is already [available ](https://pub.dev/packages/secure_biometric_storage/versions/0.3.0-nullsafety.1) since a while.
